---
deployment:
      tasks:
        - export DEPLOYPATH=/home2/laurghit/public_html/
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp score.js $DEPLOYPATH
        - /bin/cp -R * $DEPLOYPATH